openapi: 3.0.3
info:
  title: Autotrading Backend API
  description: API for managing persons and retrieving individual person details.
  version: 1.0.0

servers:
  - url: https://localhost:8080

tags:
  - name: Persons
    description: Operations related to persons

paths:
  /persons:
    post:
      tags:
        - Persons
      summary: Create a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Person created

    get:
      tags:
        - Persons
      summary: Retrieve all persons
      responses:
        '200':
          description: A list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '204':
          description: No persons found

    put:
      tags:
        - Persons
      summary: Update a person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '204':
          description: Person updated

  /persons/{id}:
    get:
      tags:
        - Persons
      summary: Retrieve a single person with full metadata
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Person details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDetails'
        '404':
          description: Person not found

    delete:
      tags:
        - Persons
      summary: Delete a person
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Person deleted

components:
  schemas:
    Person:
      type: object
      required: [first_name, last_name, email, phone_number]
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        phone_number:
          type: string
        password:
          type: string
          description: Required only for creation

    PersonDetails:
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: object
          properties:
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            reason_update:
              type: string
